### ISSUE TITLE
Bug: text-justify not working

### ISSUE THREAD

**Issue by feruzm** [ecency/ecency-mobile#2157] opened 2022-01-23 17:04 UTC
With new update on native rendering, `<div class="text-justify">text</div>` is not properly supported on content render.

post example: https://ecency.com/hive-142159/@dayatsiaulia/raja-si-uroe-monomad
Another similar but slightly different bug report: 
https://ecency.com/hive-125125/@liveofdalla/re-ecency-2022122t184647364z
https://discord.com/channels/385034494555455488/385448634197737484/935417936284385400

**Comment by noumantahir** [comment] 2022-01-26 19:15
After struggling with it for a while it seems the issue is coming from react-native-render-html package, I have created a comment on similar issue on their github repo. Let's hope they come back with a solution, meanwhile removing `textAlign:'justify'` prop for Android side as instead justifying it is rather clipping the like ends.

https://github.com/meliorence/react-native-render-html/issues/202#issuecomment-1022509101

**Comment by noumantahir** [comment] 2022-01-27 07:25
@feruzm 
Digging more deep revealed, it is essentially being caused because we made text selectable...it's not an issue with react-native-render-helper but coming from react-native itself...

if we remove the selectable prop, the text-justify starts working...

reference issue.
https://github.com/facebook/react-native/issues/30332

**Comment by feruzm** [comment] 2022-01-27 07:42
@noumantahir we really need text selection, paragraph selection was a compromise but even that causing issue seem bit hassle, perhaps we should rewrite some part of native-render-helper to add support for that?

**Comment by noumantahir** [comment] 2022-01-27 08:22
@feruzm how about we put it as a feature request and move forward based on what render html have to say about that...

It successful, it would fix the selectable issue on iOS, but that would still not solve the text-justify issue on android as it is rather coming from react-native itself.

**Comment by noumantahir** [comment] 2022-01-27 08:39
apprently for the current issue in hand, no address it even though it has been raised multiple times on react-native repo...

**Comment by noumantahir** [comment] 2022-01-27 08:40
closed by mistake, reopened again

**Comment by feruzm** [comment] 2022-01-27 08:41
@noumantahir Couldn't we shrink post body a bit to get around it for now?

**Closed** 2022-01-27 09:01 UTC
Labels: bug
