### ISSUE TITLE
Image is not being uploaded through Picsart.

### ISSUE THREAD

**Issue by PeerzadaZeeshan** [ecency/ecency-mobile#464] opened 2019-01-19 03:31 UTC
#### Brief description of bug:
I ooened an app and edited an post. After finishing my edit, i tried to upload an image through **Picsart Camera**. I tried to capture an image on that time through **Picsart Camera**, but it is not being uploaded.
#### How to reproduce:
* Open an app and click on **➕** to add a post.
* Then click on **✏️** icon to add post.
* After that click on **🖼️** image icon to add image.
* Then click on **Capture a photo** to capture photo.
* Then choose **Picsart camera**.
* Capture an image and click on the **Arrow** to upload image.
* App is not being able to upload the image. As by default when we add any image it shows an uploading icon on the top right corner and image is uploaded. But image captured through **Picsart**, it doesn't show any action and image is not being uploaded.
#### Expected behavior:
As usual it uploads every image also it uploads an image captured through direct phone camera. Like that it must be able to upload an image captured through **Picsart Camera**.
#### System information:
* Android: Redmi Y2/S2
* Operating system: 8.1.0
#### Video of the bug:
https://youtu.be/9BsXekDk6EA

**Comment by feruzm** [comment] 2019-01-22 11:07
Thanks @PeerzadaZeeshan! If you use default camera, it should work as intended. Interesting, to see other application, perhaps they provide different image format or path. We will take a look...

**Comment by PeerzadaZeeshan** [comment] 2019-01-22 11:14
@feruzm, yes i know if we use default camera it works as intended. But it must be able to work using picsart.
As i used picsart for other apps it worked as usual except this.

**Comment by feruzm** [comment] 2019-01-22 11:20
ok, we will check in future releases, please check milestone this issue is assigned to and check back after fix is released!

**Closed** 2020-12-15 11:37 UTC
